version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: meu_projeto_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    container_name: meu_projeto_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    command: ["npm", "run", "start"]

  db:
    image: postgres:15
    container_name: meu_projeto_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
